# Generated by Django 3.2.13 on 2022-12-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberInput', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер Входящий')),
                ('user', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Подпись пользователя')),
                ('nomenklatura', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номенклатура')),
            ],
        ),
        migrations.CreateModel(
            name='InputJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberInput', models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('14', '14')], max_length=1000, null=True, verbose_name='Номер Входящий')),
                ('dateReg', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('correspondent', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Кореспондент (откуда поступило)')),
                ('content', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Краткое содержание')),
                ('executor', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Исполнитель')),
                ('mark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Отметка о получении')),
                ('nomenklatura', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номенклатура')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office_dev.signature')),
            ],
        ),
    ]
